# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miniclawd < Formula
  desc "Multi-platform AI chat bot"
  homepage "https://github.com/yifanes/miniclawd"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.1.1/miniclawd_0.1.1_darwin_amd64.tar.gz"
      sha256 "64a14d25ba745d1eb5d68ef64e9fa20a116e21278cb6759e4c4168ebc213b88f"

      def install
        bin.install "miniclawd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.1.1/miniclawd_0.1.1_darwin_arm64.tar.gz"
      sha256 "668b95cf4ef82220835e07c396258e00bddecf4cb8dd1f408dc3a310b47a1c5b"

      def install
        bin.install "miniclawd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.1.1/miniclawd_0.1.1_linux_amd64.tar.gz"
      sha256 "6867ac571705876758f2064181984ba554efbafc05ae81a7cb825bbcbc82f6bb"
      def install
        bin.install "miniclawd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.1.1/miniclawd_0.1.1_linux_arm64.tar.gz"
      sha256 "09a1cd23d5f79085a3bbbb5c8fa72a6bf6eb8810ad5a40615f687d953abd4001"
      def install
        bin.install "miniclawd"
      end
    end
  end

  test do
    system "#{bin}/miniclawd", "version"
  end
end
