# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miniclawd < Formula
  desc "Multi-platform AI chat bot"
  homepage "https://github.com/yifanes/miniclawd"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.2.1/miniclawd_0.2.1_darwin_amd64.tar.gz"
      sha256 "dbc9922ac2f3e85e1fd9ff24bfa8137c745514780ecdbf1f3e1934b9671295e4"

      define_method(:install) do
        bin.install "miniclawd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.2.1/miniclawd_0.2.1_darwin_arm64.tar.gz"
      sha256 "c271b162bfa8a2c5ff42199f338c3f0c49b56fbe265fd24c9f7068f2ef74a67d"

      define_method(:install) do
        bin.install "miniclawd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.2.1/miniclawd_0.2.1_linux_amd64.tar.gz"
      sha256 "86ba87936bdb0ff06e675467e572fe14ece088e95596b606526a0603994d2158"
      define_method(:install) do
        bin.install "miniclawd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yifanes/miniclawd/releases/download/v0.2.1/miniclawd_0.2.1_linux_arm64.tar.gz"
      sha256 "4070f355de7e676c18301bbdb812295acd0d6f4367a6e15f2de08c7f9c97104c"
      define_method(:install) do
        bin.install "miniclawd"
      end
    end
  end

  test do
    system "#{bin}/miniclawd", "version"
  end
end
